[package]
name = "rust_craft"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
#bevy_rapier3d = "0.28.0"
leafwing-input-manager = "0.16.0"

[profile.dev]
opt-level = 0
overflow-checks = false
lto = false
